## This is needed for Class Level Route configuration
service:
  first:
    uri: http://localhost:8010
  second:
    uri: http://localhost:8020

logging:
  level:
    org.springframework.security: DEBUG

spring:
  cloud:
    gateway:
      ## Instead of following configuration, we can use Class level configurations(GatewayConfig.java)
      routes:
        - id: get-heroes
          uri: http://localhost:8010
          predicates:
            - Path=/api/heroes/**
        - id: get-vigilante
          uri: http://localhost:8020
          predicates:
            - Path=/bad-guys/vigilante/**
      ##------------------
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: [ "GET", "POST", "PATCH", "PUT", "DELETE", "OPTIONS" ]
            allowedHeaders: [ "Authorization", "Content-Type", "Accept" ]
            maxAge: 3600

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/<<Tenant ID>>/v2.0
          jwk-set-uri: https://login.windows.net/common/discovery/keys
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true